# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Intro to Computer Engineering"
course: "CSE 132"
semester: "Fall 2021"

# baseurl: "/~SEAS-SVC-CSE132"
# baseurl: "/~roger/test/fall2021"

# exclude: [p.sh, push.sh]
